config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :statistics
  resources :bases
  resources :customers
  resources :hoagies
  resources :orders
  resources :ordered_additionallies

  resources :reviews do
    resources :comments
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base.rb
class Base < ApplicationRecord
  has_many :hoagies
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer, foreign_key: 'customer_id'
  belongs_to :review, foreign_key: 'review_id'
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :comments
  has_many :orders
  has_many :reviews
end

app/models/hoagie.rb
class Hoagie < ApplicationRecord
  belongs_to :base, foreign_key: 'base_id'
  belongs_to :order, foreign_key: 'order_id', optional: true
  has_many :ordered_additionallies
  has_many :ingredients, through: :ordered_additionallies
  validates :base_id, presence: true, numericality: { only_integer: true }
  validates :count, presence: true, numericality: { only_integer: true }
  accepts_nested_attributes_for :ordered_additionallies
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ordered_additionallies
  has_many :hoagies, through: :ordered_additionallies
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer, foreign_key: 'customer_id'
  has_many :hoagies
  accepts_nested_attributes_for :hoagies
end

app/models/ordered_additionally.rb
class OrderedAdditionally < ApplicationRecord
  belongs_to :hoagie, foreign_key: 'hoagie_id', optional: true
  belongs_to :ingredient, foreign_key: 'ingredient_id'
  accepts_nested_attributes_for :ingredient
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer, foreign_key: 'customer_id'
  has_many :comments, dependent: :destroy
  mount_uploader :selfie, SelfieUploader
end

app/controllers/bases_controller.rb
class BasesController < ApplicationController
  http_basic_authenticate_with name: "admin247", password: "secret!", except: [:index, :show]
  def index
    @bases = Base.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  http_basic_authenticate_with name: "admin247", password: "secret!", except: [:index]
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)

    if @review.save
      redirect_to @review
    else
      render 'new'
    end
  end

  def update
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to @review
    else
      render 'edit'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to reviews_path
  end

  private
  def review_params
    params.require(:review).permit(:customer_id, :title, :text, :grade, :selfie)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_random_image
    image_path_prefix = "app/assets/images/"
    image_files = Dir.glob("#{image_path_prefix}selfies/*")
    image_files.sample.split(image_path_prefix)[1]
  end
end

app/helpers/bases_helper.rb
module BasesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/hoagies_helper.rb
module HoagiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/reviews/_form.html.erb
<%= form_with scope: @review, url: reviews_path, local: true do |form| %>

  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@review.errors.count, "error") %> prohibited
        this review from being saved:
      </h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :customer_id %><br>
    <%= form.text_field :customer_id %>
  </p>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.label :grade %><br>
    <%= form.text_field :grade %>
  </p>
  <p>
    <%= form.label :selfie %><br>
    <%= form.file_field :selfie %>
  </p>
  <p>
    <%= form.submit %> | <%= link_to 'Back', reviews_path %>
  </p>
<% end %>

app/views/reviews/index.html.erb
<h1>Customer Review</h1>
<%= link_to 'New Order', new_order_path %> |
<%= link_to 'New Review', new_review_path %>

<table>
  <tr>
    <th>Customer</th>
    <th>Image</th>
    <th>Grade</th>
    <th>Title</th>
    <th>Review Text</th>
    <th>Latest Comment</th>
    <th>More Comments</th>
    <th>No. in Total</th>
  </tr>
  
  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.customer_id %></td>
      <td class="selfie"><%= review.selfie = image_tag(get_random_image, :size => "175x120") %></td>
      <td><%= review.grade %></td>
      <td><%= review.title %></td>
      <td><%= review.text %></td>
      <td><%= Comment.where(review_id: review).pluck(:text).last %></td>
      <td><%= link_to 'See Comments', review_path(review) %></td>
      <td><%= Comment.where(review_id: review).count.to_i %></td>
    </tr>
  <% end %>
</table>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= render 'form' %>

app/views/reviews/show.html.erb
<p>
  <strong>Selfie:</strong>
  <%= @review.selfie.url %>
</p>
<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>
<p>
  <strong>customer_id:</strong>
  <%= @review.customer_id %>
</p>
<p>
  <strong>Text:</strong>
  <%= @review.text %>
</p>
<p>
  <strong>grade:</strong>
  <%= @review.grade %>
</p>
<h2>Comments</h2>
<%= render @review.comments %>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
<%= link_to 'Back', reviews_path %>